---
- name: Run "docker-compose up -d web_dev"
  hosts: localhost
  become: false
  tasks:
    - name: Run "docker-compose up -d web_dev"
      shell: "cd /home/dan/code/cuddly-disco && /usr/local/bin/docker-compose up -d"
    - name: Check if the web_dev container is running
      docker_container_info:
        name: web_dev
      register: container_status
    - debug:
        var: container_status



#In this playbook, the first task uses the shell module to check if the web_dev container is running by using the docker ps command. 
#It filters the output to only show container names that match web_dev and it only returns the name of the container.
#The register option is used to save the output of the command in a variable called `container