---
version: '3'
networks:
  newasgard:
    driver: macvlan
    driver_opts:
      parent: enp0s3
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.254
services:
  web_dev:
    build:
      context: .
      target: dev
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - .:/usr/local/apache2/htdocs
    networks:
      newasgard:
        aliases:
          - 192.168.1.17
  web_prod:
    build:
      context: .
      target: prod
    ports:
      - "8081:80"
      - "8444:443"
    volumes:
      - .:/usr/local/apache2/htdocs
#new feature branch macvlan created as promiscous mode required hardware changes. Still works well though. 
