---
version: '3'
networks:
  newasgard:
    driver: ipvlan
    driver_opts:
      parent: enp0s3
      mode: l3
services:
  web_dev:
    build:
      context: .
      target: dev
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - .:/usr/local/apache2/htdocs
    networks:
      newasgard:
        ipv4_address: 192.168.94.2/24
  web_prod:
    build:
      context: .
      target: prod
    ports:
      - "8081:80"
      - "8444:443"
    volumes:
      - .:/usr/local/apache2/htdocs
    networks:
      newasgard:
        ipv4_address: 192.168.95.2/24
